[project]
name = "realtime-tts-stream"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "edge-tts>=7.2.7",
    "fastapi[all]>=0.129.0",
    "python-multipart>=0.0.22",
    "uvicorn>=0.40.0",
]
